[package]
edition = "2018"
name = "toy_regex"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
structopt = "0.3"

[profile.release]
debug = 1
