name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/cache_cargo
      - name: Run Build
        run: cargo build --verbose

  clippy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/cache_cargo
      - run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/cache_cargo
      - name: Run test
        run: cargo t --verbose
 